### ISSUE TITLE
探讨

### ISSUE THREAD

**Issue by dakango** [storipress/wordpress-sdk#9]
作者您好, 有个疑问, WordPress 文档里面写的是用 post 调用文章更新 api, 您为什么用 patch 呢? 某些版本的 wordpress, 使用 patch 好像是不可以的
![image](https://github.com/storipress/wordpress-sdk/assets/23118182/5ebd5d73-8022-4732-9c4d-2ef1cbe310cd)

**Comment by bepsvpt** [comment]
感謝您的回報，之前沒有注意到，已在 1.0.18 修正此錯誤。
